### ISSUE TITLE
GARTER_SLOP need not be added when garter carriage is not in use

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-firmware#100]
Perhaps I don't have a full understanding of what `GARTER_SLOP` is intended to do, but going by the name it seems to be something that should apply only when `Knitter::m_carriage == Garter`. Instead we have:

https://github.com/AllYarnsAreBeautiful/ayab-firmware/blob/28782e339c2677fee23227a34b854447c09afde7/src/ayab/knitter.cpp#L224-L227

see also #86

**Comment by dl1com** [comment]
@clholgat I think GARTER_SLOP was introduced by you, could you please elaborate if we need this for every carriage or only for Garter?

**Comment by clholgat** [comment]
The garter slop is needed to determine whether or not we have a garter carriage. If we didn't have it, we'd decide which carriage we had when the first needle passed the sensor. For the garter carriage we need to see both.

I turned it all the way down, it's only 2 needles IIRC so it shouldn't delay start too much.

**Comment by t0mpr1c3** [comment]
Thanks for the explanation. Sounds like we can close this issue.
