### ISSUE TITLE
reqTest bug

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-firmware#171]
The firmware expects reqTest to be a 2-byte message with the second byte specifying machine type, but the API specifies a 1-byte message, and that was what the desktop is been sending.

This bugfix changes the firmware to be consistent with APIv6 and may close https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/461

**Comment by jonathanperret** [comment]
Fix tested as working.
