### ISSUE TITLE
KH930: garter carriage starting from the left; pattern is displaced by 24 needles.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-firmware#180]
KH930, garter carriage pattern is displaced by 24 stitches to the left.

AYAB software version: 0.99 rc1 Aug 6 2023
Computer/OS: Windows 7
Knitting machine: KH930
AYAB hardware: Interface

KH930 KG89 garter carriage, starting from the left.
Open the uC3 image from the samples
Set all UI settings to defaults, except set L40 and R20 as the start and end needles
Set needles in work from L40 - R20. 
Cast on and knit some stockinette rows with the K carriage to get started.
Thread up the G carriage and start from the left.
Let it knit at least 6 rows.
Expected: it should be following the pattern exactly. The image is 30 pixels wide, so should knit from L15 to R15, with the tail of the mu character starting on R14-R15 on row 1.
Actual: it does make the image correctly, but the whole image is displaced 24 needles to the left. In the photo I'm pointing at where it should have started.
(I haven't tried the whole 200 needles yet with the G carriage on a 930, nor starting the G carriage from the right. Might as well wait for this bug and #176 to be addressed.)
![IMG_2473 copy](https://github.com/AllYarnsAreBeautiful/ayab-firmware/assets/24358225/9e757af4-0c61-4df4-9f3c-fa67aaf50dd4)
![IMG_2478 copy](https://github.com/AllYarnsAreBeautiful/ayab-firmware/assets/24358225/c03e850f-fc03-4a03-beb4-1ab134d64932)

**Comment by clholgat** [comment]
Works correctly for the kg-89
