### ISSUE TITLE
Using clang-format for automatic code formatting

### ISSUE THREAD

**Issue by Sturla22** [AllYarnsAreBeautiful/ayab-firmware#20]
Formatting the entire repository with clang-format will lead to more uniform code formatting across the project and make code reviews easier.

Although the tool has many options, the default options seem to be OK, are there any wishes or preferences for customizing the formatting applied?

The online [clang-format configurator](https://zed0.co.uk/clang-format-configurator/) can be used to explore different settings.

The only setting I would prefer customizing with respect to the default is 	`AllowShortFunctionsOnASingleLine`, I don't think single line functions are very readable.

**Comment by chris007de** [comment]
Merged into v1.0-dev
