### ISSUE TITLE
Unit testing for host machines

### ISSUE THREAD

**Issue by Sturla22** [AllYarnsAreBeautiful/ayab-firmware#22]
Adding unit tests that can run without the hardware should allow for an easier development experience, as well as potentially helping to make it faster.

I have looked into the [catch2](https://github.com/catchorg/Catch2) testing framework and a mock library called [trompeloeil](https://github.com/rollbear/trompeloeil), so far my experiments have used CMake as the build tool.

I think writing tests for one module at a time would be the best approach, I expect that the knitter class will take longer than the others due to its size and complexity.

The modules are (in order of planned implementation):

- [x] Beeper (#25)
- [x] Encoders (#23)
- [x] Solenoids (#30)
- [x] Sketch file (#30)
- [x] Knitter (#30)

Any opinions on what framework/tools to use or other organizational ideas?
Does anyone know how to eventually add the tests to Travis CI?

**Comment by chris007de** [comment]
> Any opinions on what framework/tools to use or other organizational ideas?

I recently had a positive experience with Arduino Unit Testing with GUnit while Gmocking the Arduino-specific calls with [arduino-mock](https://github.com/bt-trx/arduino-mock) in [this project](https://github.com/bt-trx/firmware/tree/master/test).
The Arduino-Mock library is pretty straight forward and easily extendable, while GUnit is a somewhat established "standard" framework. Being able to compile the tests using a bare gcc without any Arduino/Atmel dependent stuff is really nice and is an easy setup.
Perhaps you can have a look into the the bt-trx project test setup and give your opinion, I am also open for new approaches, as long as the framework is not too exotic :)

> Does anyone know how to eventually add the tests to Travis CI?

Yes, in the project mentioned above, we are running the unit tests with travis: https://github.com/bt-trx/firmware/blob/master/.travis.yml#L16
