### ISSUE TITLE
Enable to start from the right-hand side of the machine as well

### ISSUE THREAD

**Issue by dl1com** [AllYarnsAreBeautiful/ayab-firmware#31]
Please be aware of the discussion in https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/247.

> @Adrienne200 Most Brother instructions have you starting from the left, but it also works starting from the right. Their instructions for restarting after a mistake allow restarting from either end. The CK35 manual says you can start from either end. Instructions for using the single-bed color changer have you doing the setup row starting from the right; starting from the right would be useful for case #204.

**Comment by t0mpr1c3** [comment]
Implemented in https://github.com/AllYarnsAreBeautiful/ayab-firmware/commit/2ff00a115196c45609bfa5240f9555625973d6c0
