### ISSUE TITLE
Generic makefile for building firmware binaries

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-firmware#5]
Currently, the firmware builds for the various favors (910/930, uno/mega) have to be done manually. A generic makefile script shall take care of building a defined favor or all possible favors to ease integration in the firmware repository generation process.

**Comment by Sturla22** [comment]
Are you happy with the current state of this (in v1.0-dev)? I'm thinking this can maybe be closed..

**Comment by t0mpr1c3** [comment]
Awesome work, Sturla. The generic makefile looks a massive improvement in the build process.

**Comment by chris007de** [comment]
:+1:
