### ISSUE TITLE
The double-beep at the end of a pattern is not clearly different from the single beep

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-firmware#8]
_From @Adrienne200 on December 16, 2016 5:54_

The double-beep was not different enough from the single on the original AYAB, and is even less distinct on the EMSL board. The single sound is slightly longer than before, and merges with the second beep.

_Copied from original issue: AllYarnsAreBeautiful/ayab-desktop#164_

**Comment by chris007de** [comment]
We'll test some other settings for the beeps to achieve a better distinguishment between single and double beep.

**Comment by Adrienne200** [comment]
The double beep (or long beep) is much clearer now. But the EMSL boards had had an improved sound, it is now back to a plain buzz.  How would it sound with a longer double-sound but leaving the usual sound as it was?

**Comment by Adrienne200** [comment]
This can be closed. The sound was put back to the EMS version for the final release of 0.9 and is more clearly different than it was in 0.8.  It occurs after the last row has been selected but before you knit it, which is OK.
