### ISSUE TITLE
Publish pages

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-firmware#89]
The repo settings need to be changed so that the doxygen makedocs on branch gh-pages get published. After this is done, they should be visible at https://ayab-knitting.com/ayab-firmware/html/

To see what they should look like, navigate to https://t0mpr1c3.github.io/ayab-firmware/html/

**Comment by dl1com** [comment]
Do you know which settings we need to make it work?
Besides that: Shouldn't this step only run i.e. when making a release, not on every PR?

**Comment by t0mpr1c3** [comment]
From the repository Settings select Pages, and then under "Build and deployment" select Deploy from Branch >> gh-pages / root

Yes, it doesn't need to run every single PR.

**Comment by t0mpr1c3** [comment]
close as completed

**Comment by t0mpr1c3** [comment]
Could do with a file http://ayab-knitting.com/ayab-firmware/index.html that redirects to http://ayab-knitting.com/ayab-firmware/html/

**Comment by dl1com** [comment]
> Could do with a file http://ayab-knitting.com/ayab-firmware/index.html that redirects to http://ayab-knitting.com/ayab-firmware/html/

In the Github pages settings, the only choices are / or /docs. So it should be sufficient to generate the documentation in / or /docs instead of /html.

**Comment by t0mpr1c3** [comment]
Is that actually possible in Doxygen? By default it generates the HTML under /html
